title: Today I Learned
tagline: A blog dedicated to small knowledge snippets I learn every day.
author: Zoltán Reegn
url: https://reegnz.github.com/til

social_links:
  twitter: zoltanreegn
  github: reegnz
  keybase: reegnz

theme: minima

show_excerpts: true

minima:
  date_format: "%Y-%m-%d %H:%S"

header_pages:
- _pages/about.md
- _pages/archive.md

include:
- _pages

exclude:
- .gitignore
- README.md
- LICENSE

plugins:
- jemoji
- jekyll-feed
- jekyll-seo-tag
