title: Today I Learned
tagline: A blog dedicated to small knowledge snippets I learn every day.
url: reegnz.github.com/til

show_excerpts: true

social_links:
  twitter: zoltanreegn
  github: reegnz
  keybase: reegnz

theme: minima
minima:
  date_format: %FT%R

plugins:
- jekyll-feed
- jekyll-seo-tag
